language: scala

jdk:
  - openjdk11

scala:
  - 2.13.4

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

env:
  - LOG_LEVEL=WARN

script:
  - sbt ++$TRAVIS_SCALA_VERSION build
